### ISSUE TITLE
Sentryhook panics if no context is provided to the logger

### ISSUE THREAD

**Issue by phumberdroz** [makasim/sentryhook#6]
https://github.com/makasim/sentryhook/commit/a900aa94e371f008983186f02873284eac24fd8a#diff-e6e832ce9eeb51105105595ce823c9b28734de30c345d2b21dddb4b0fa786926R83

This piece panics if the logrus.Entry does not have a context.

**Comment by makasim** [comment]
fixed in https://github.com/makasim/sentryhook/pull/5
